name: Build and Test App
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secret.DOCKER_PASSWORD}}
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/CI_Continuous-Integration-test
    - name: Push the Docker image
      id: push
      run: docker push ${{secrets.DOCKER_USER}}/CI_Continuous-Integration-test